### ISSUE TITLE
Main page Activity results table background color showing white.

### ISSUE THREAD

**Issue by MostHated** [StylishThemes/GitHub-Dark#1082]
I went to the main page of Github an noticed that the listings/follower information and what not are no longer correctly colored. I cut the left side off a bit just to be respectful and hide the names, but I believe it should still be fairly easy to see where the discoloration is occurring.

Github-Dark theme version. v2.07 using Stylus plugin
* **Browser**: Firefox
* **Operating System**: Windows 10
* **Link to page with the issue**: http://github.com
* **Screenshot**:  ![](https://i.imgur.com/PNZaUix.png)

**Comment by xt0rted** [comment]
Are you using any browser extensions for GitHub such as Refined GitHub?

**Comment by MostHated** [comment]
Yes, I am using Refined Github. Should I try disabling it?

**Comment by MostHated** [comment]
I apologize, I forgot to mention, I am also using the "Github Wide" theme, but I just disabled it to test, and the coloration was still off.

**Comment by silverwind** [comment]
This is coming from RGH but for some reason is not extracted from the Chrome extension.

**Comment by MostHated** [comment]
Ah, I see. Should I go ahead and put in a ticket with them?

**Comment by silverwind** [comment]
Fixed it, it seems a "breaking" change on their end invalidated all our styles for it.

@fregante: RGH seems to no longer set `.refined-github` on `html`. Is that intentional?

**Comment by MostHated** [comment]
Great news, and thanks for probably the most prompt responses and fixes to something I have ever experienced, lol.

**Comment by xt0rted** [comment]
With v20.2.28 in Chrome I'm still seeing the `.refined-github` class on the `html` element but in v20.3.3 in FireFox it's no longer there.

**Comment by silverwind** [comment]
Yes, it appears to be a very recent change. For some reason RGH is having troubles keeping the Chrome extension up to date recently.

**Comment by xt0rted** [comment]
Stylus has been having similar issues. Can't wait for the next update of that.

**Comment by silverwind** [comment]
Damn, this affects non-RGH frontpage now. The only difference in HTML that I see is a `class=" "` on the HTML node.

**Comment by silverwind** [comment]
Dirty workaround added.

**Comment by silverwind** [comment]
https://github.com/sindresorhus/refined-github/issues/2857

**Comment by xt0rted** [comment]
It might be my settings but I'm not seeing the empty class attribute.

![image](https://user-images.githubusercontent.com/831974/75830259-5580fa80-5d7e-11ea-9ca4-1adf112b1430.png)

**Comment by silverwind** [comment]
You're right it's not there on page load but it did appear some times after for me. Very weird. Let's wait on https://github.com/sindresorhus/refined-github/issues/2857. I'll revert the last change.

**Comment by fregante** [comment]
Fixed in Refined GitHub 20.3.4

**Comment by silverwind** [comment]
@fregante Thanks. Suggestion: Wrap all your "feature" code in individual try-catch blocks. That way, if one of them breaks, the whole extension will not break down.

**Comment by fregante** [comment]
That’s not what broke. It was a dependency with code that makes Firefox ignore the whole file. Add this regex inside a try catch and see if Firefox loads it: `/(<m>a)/`

**Comment by silverwind** [comment]
Indeed, try-catching a dependency is more tricky, but not impossible with async `import()`.

That said, I hear Firefox should gain lookbehind soonish. It's a shame it took them so long.
