### ISSUE TITLE
Inverting rendered GitHub equations

### ISSUE THREAD

**Issue by Alex-Muirhead** [StylishThemes/GitHub-Dark#1228]
When rendering equations on a GitHub `README.md` where the equations are source from `render.githubusercontent.com/render/math`, the equations are not inverted correctly, and appear with white text AND background. 

I believe this can be fixed by replacing 
```css
img[src*="//render.githubusercontent.com/render/math"] {  /* Line: 29616 */
  filter: invert(90%);
}
```
with 
```css
img[src*="//render.githubusercontent.com/render/math"] {  /* Line: 29616 */
  filter: invert(90%);
  background-color: rgb(255, 255, 255);
}
```
to override the GitHub css, which attempts to set the background to `rgb(24, 24, 24)`. 

I'm unsure if I can just make a pull request to fix this, as I want to make sure it's not a breaking change that I'm not seeing.

* **Browser**: Firefox 81.0
* **Operating System**: Windows 10
* **Link to page with the issue**: Any valid GitHub page with images with source `render.githubusercontent.com/render/math`
* **Screenshot**: 
![image](https://user-images.githubusercontent.com/15205931/95004026-5b4b0100-0629-11eb-9919-81b81d0d338e.png)

**Comment by the-j0k3r** [comment]
related https://github.com/StylishThemes/GitHub-Dark/search?q=render.githubusercontent.com%2Frender%2Fmath

This was fixed before re: https://github.com/StylishThemes/GitHub-Dark/issues/1060

**Comment by silverwind** [comment]
Any link to a page with this issue?

**Comment by Alex-Muirhead** [comment]
> 
> 
> related https://github.com/StylishThemes/GitHub-Dark/search?q=render.githubusercontent.com%2Frender%2Fmath
> 
> This was fixed before re: #1060

@the-j0k3r my apologies, I didn't see that issue in my search. However, the issue still appears with the latest update.

@silverwind It appears on all READMEs with math equations using `render.githubusercontent.com/render/math`, so an example would be [https://github.com/MECH3750/2020-Tutorials/tree/master/Week%207](https://github.com/MECH3750/2020-Tutorials/tree/master/Week%207), which is the source of the screenshot. 

This is my configuration of GitHub Dark, if that is relevant. 
![image](https://user-images.githubusercontent.com/15205931/95035538-bb64a480-0708-11eb-8f8f-9310fbfa8a0e.png)

**Comment by the-j0k3r** [comment]
OK found a way to fix this issue and not break #1060 which was also broken due to **someone** editing the working regex and breaking it.
