### ISSUE TITLE
Some border issues

### ISSUE THREAD

**Issue by Geeyun-JY3** [StylishThemes/GitHub-Dark#1287]
* **Browser**: Cent Browser 4.3.9.248 (64-bit) (Chromium 86.0.4240.198), Chrome 87.0.4280.141 (Official Build) (64-bit)
* **Operating System**: Windows 10 20H2 19042.685
* **Link to page with the issue**: 
	1. Dashboard: https://github.com/
	2. PR: https://github.com/sindresorhus/refined-github/pull/3837
	3. User's own comment box
* **Screenshot**:
	1.  Two rounded corners of the `Show more` button in the dashboard is not sleek.
![gif](https://user-images.githubusercontent.com/49396421/104121336-409acd80-5378-11eb-8545-f0397401669c.gif)
I guess this bug related to GitHub's native light theme:
![gif1](https://user-images.githubusercontent.com/49396421/104121414-067dfb80-5379-11eb-85b8-210f0ec0bf3d.gif)
Casue its native dark theme looks good: 
![native_dark_theme](https://user-images.githubusercontent.com/49396421/104121573-4b566200-537a-11eb-95c4-7a0a29feeef0.gif)
	2. A horizontal rule in mergeability box:
![image](https://user-images.githubusercontent.com/49396421/104121758-ad639700-537b-11eb-9038-4444a7c80c7e.png)
![image](https://user-images.githubusercontent.com/49396421/104114287-9f8f2100-533d-11eb-8668-c4ff9e243e04.png)
	3. User's own comment box
![image](https://user-images.githubusercontent.com/49396421/104121982-3deea700-537d-11eb-9312-642fe0851df1.png)
A little bit difference if zoomed in
![image](https://user-images.githubusercontent.com/49396421/104122021-80b07f00-537d-11eb-8387-aa8cfec01414.png)

**Comment by Geeyun-JY3** [comment]
The border of Refined GitHub’s pinned issue list layout also has this bug (enable `clean-pinned-issues`)
![gif](https://user-images.githubusercontent.com/49396421/104674044-e5712e00-571d-11eb-8572-fc60c5cef291.gif)

**Comment by the-j0k3r** [comment]
iii: if you see the alignment issue when zoomed in its a upstream bug, you dont actually say in which conditions iii is manifested.

you may want to also test with https://github.com/StylishThemes/Feature-Override-Styles/blob/master/github-custom-border-radii.user.css installed

**Comment by Geeyun-JY3** [comment]
iii seems got fixed by GHD now…

**Comment by the-j0k3r** [comment]
Still looks like a border-radius issue that maybe fixed with the style I mentioned.

**Comment by Geeyun-JY3** [comment]
> Still looks like a border-radius issue that maybe fixed with the style I mentioned.

Tested. Can't fix it.

**Comment by the-j0k3r** [comment]
and have you disabled refined github to see if it its not it causing it?

**Comment by Geeyun-JY3** [comment]
> and have you disabled refined github to see if it its not it causing it?

Tested. RGH didn't cause it.

**Comment by the-j0k3r** [comment]
Well I can t help you further, I dont use style anymore and as such cant really fix it for you, so you'll have to wait for someone to get to it.

Also I can say with some certainty that some border issues you reported exist upstream, but due to styling colors the issues arent so on your face obvious, though some issues with borders may be caused by this style because it adds many opinionated overrides that cause issues.

**Comment by MarcelCoding** [comment]
Also for diffs in e.g. pull requests or commits: 
![image](https://user-images.githubusercontent.com/34819524/111051082-cdcdd180-8450-11eb-8e95-70dc847e10d5.png)

**Comment by the-j0k3r** [comment]
@MarcelCoding I can recommend you choose in settings background ---> none, these issues are related to backgrounds where there shouldn't be any.

**Comment by MarcelCoding** [comment]
@the-j0k3r  This actually does not fix the bug. In the developer tools I tried to add `overflow: hidden` (on the element with the border) and it solved the problem.
![image](https://user-images.githubusercontent.com/34819524/111063954-bd017800-84b1-11eb-8d68-da8c802cb0ee.png)

**Comment by silverwind** [comment]
> Dashboard: https://github.com/

Is fixed, the others I could not reproduce.

**Comment by MarcelCoding** [comment]
@silverwind this error still occurs: https://github.com/cryptic-game/java-backend/pull/277/files
![image](https://user-images.githubusercontent.com/34819524/111377991-95710200-86a1-11eb-967f-520109879333.png)

**Comment by silverwind** [comment]
Can't see an issue on that expander button besides inaccurate border radius, but that's GH's fault.

<img width="66" alt="image" src="https://user-images.githubusercontent.com/115237/111378864-b7b74f80-86a2-11eb-8d45-8d818069e83e.png">

**Comment by MarcelCoding** [comment]
Maybe it depends on the browser? I use firefox

**Comment by silverwind** [comment]
Unlikely. Try with latest version which has some fixes around diffs, otherwise link some more pages with such issues.

**Comment by MarcelCoding** [comment]
I've just updated the theme. Tomorrow I will post some more issues.

**Comment by the-j0k3r** [comment]
As I already said part of the issue is the image backgrounds, you cant have any selected.

**Comment by MarcelCoding** [comment]
![image](https://user-images.githubusercontent.com/34819524/111466071-1b815d00-8723-11eb-9ad2-0a04aa05cda7.png)
https://github.com/spring-projects-experimental/spring-native/commit/863b80cd2b1fbcc137d5c70c72c8e92c03c79e0c

No matter what background I select, the background is always overlapping.

**Comment by the-j0k3r** [comment]
> No matter what background I select, the background is always overlapping.

It must be set to none.

![Capture](https://user-images.githubusercontent.com/31389848/111482681-6ce61800-8734-11eb-9cb5-7584321a34d3.PNG)

**Comment by MarcelCoding** [comment]
I don't know what I am doing wrong. I am gonna keep it as it is. I tried every background including `none`. Thank you for your help.

**Comment by silverwind** [comment]
Those green backgrounds look fine again to me. It's hard to see what is actually wrong in your screenshot. Can you zoom in the page?

**Comment by MarcelCoding** [comment]
@silverwind If you open the link and hover over it you can clearly see that the blue background is overlapping.
Unfortunately I can't take screenshots while I am hovering over the element.

**Comment by MarcelCoding** [comment]
![image](https://user-images.githubusercontent.com/34819524/111685228-f1fe2980-8827-11eb-913a-e5ae89c7342f.png)

**Comment by silverwind** [comment]
Looks fine to me even when hovering. Try reinstalling the style.

<img width="335" alt="image" src="https://user-images.githubusercontent.com/115237/111698018-9c7d4900-8836-11eb-8b3f-b2d207bb0f16.png">

**Comment by MarcelCoding** [comment]
That also don't solve the problem. I will accept it as it is.
