### ISSUE TITLE
Non-Dark Commit Teaser

### ISSUE THREAD

**Issue by jodizzle** [StylishThemes/GitHub-Dark#257]
![non-dark-commit-teaser](https://cloud.githubusercontent.com/assets/672268/10470184/0ea15280-71d9-11e5-97cf-d090262f6ae4.png)

Seems to be happening on all repo pages for me.  Probably an easy fix?

**Comment by Mottie** [comment]
Hi @jodizzle!

Thanks for reporting this... it's all fixed now.

**Comment by auscompgeek** [comment]
You missed `.new-commit-teaser-contributors` (on file blob pages). :stuck_out_tongue_winking_eye:

Also, shouldn't `.new-commit-tease-sha` and `.new-commit-tease .message` be greys rather than the base colour?

**Comment by Mottie** [comment]
Actually I did catch that *after* I pushed an update LOL. Hmm, yeah, maybe those links should be grey as well.

**Comment by auscompgeek** [comment]
Yeah. Blue on blue lacks contrast and hence isn't very readable. It looks terrible as well.

**Comment by Mottie** [comment]
Ok, try that out.

**Comment by auscompgeek** [comment]
Not bad. I'd say moving `.new-commit-tease` from `#8195BE` to `#a0a0a0` wasn't entirely necessary, but it works well either way.

**Comment by jodizzle** [comment]
Looks pretty good to me as well.  Thanks!

**Comment by Mottie** [comment]
Ok, I'll update userstyles.org then :stuck_out_tongue_closed_eyes:

**Comment by auscompgeek** [comment]
GitHub pushed out another update today: s/new-//

**Comment by Mottie** [comment]
Yep, I just now updated userstyles.org
