### ISSUE TITLE
Vertical & horizontal border is the wrong color on releases page

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#733]
More pages have been getting the responsive treatment so this issue happens in both views.

* **Browser**: chrome
* **Operating System**: win10
* **Link**: https://github.com/xt0rted/AppVeyor-Dark/releases
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/44120463-6c412ad6-9fea-11e8-8429-0d3b393e883c.png)

![image](https://user-images.githubusercontent.com/831974/44120567-c2cce098-9fea-11e8-9f19-e8d43c2b8e40.png)

* **HTML of the section where the issue occurs**:

```html
<div class="release-entry">
  <div class="release pt-2 pt-md-0 pb-3 pb-md-0 clearfix label-latest">
    <div class="col-12 col-md-9 col-lg-10 px-md-3 py-md-4 release-main-section commit open float-left">
    </div>
  </div>
</div>
```

For the mobile view the issue is coming from the `.release-entry` class's `border-bottom` style, for desktop it's the `.release-main-section` class's `border-left` style.

**Comment by the-j0k3r** [comment]
I cant duplicate the horizontal line, if thats on mobile, wasnt the mobile selectors removed from main?

Anywho I added `"border-left: 2px solid #e1e4e8": "border-left: 2px solid #343434",` to generator just for kicks and it didnt pick this up at first run, Im pretty sure the color is right.

Ill give it one more try.

**Comment by xt0rted** [comment]
Both of those images are on desktop, just resize your window so the mobile view kicks in (there's mobile, tablet, and desktop on the responsive pages now).

**Comment by the-j0k3r** [comment]
See it.

```
Running "exec:generate" (exec) task
>> Warning: no declarations for border-bottom: 1px solid #d8d8d8 found!
>> Warning: no declarations for border-left: 2px solid #e1e4e8 found!
```

![capture](https://user-images.githubusercontent.com/31389848/44124854-3bfded22-a027-11e8-9504-fe6b2dc5d90e.PNG)

I think manually would be better rather than adding 3 lines to autogen

**Comment by the-j0k3r** [comment]
also this

![capture](https://user-images.githubusercontent.com/31389848/44125882-e8a17968-a02c-11e8-9629-2b95e437a397.PNG)

to fix 
```css
	.release-timeline-tags .tag-timeline-date:after {
		background-color: #545454 !important;
		border-color: #545454 !important;
	}
```

**Comment by silverwind** [comment]
I think I've fixed all release page issues, can someone confirm?

**Comment by silverwind** [comment]
Ok fixed too. We have to think about something for the media queries, we can't just pop rules from them into our generated sections.

**Comment by the-j0k3r** [comment]
Again, STILL not fixed. Now it goes back to same issue I described in https://github.com/StylishThemes/GitHub-Dark/commit/aab8df9a6bc5b2640d4012934b93a5469eda78c4

Remember until that commit EVERYTHING worked.

**Comment by the-j0k3r** [comment]
So we are clear https://github.com/StylishThemes/GitHub-Dark/blob/19aaa043998fcf4ac1889e976d20045867647622/github-dark.css#L399 that causes the breakage.

**Comment by the-j0k3r** [comment]
Also you dont need media queries in there, it was working perfectly fine without, the autogenerated en
entry above screws it all up media queries or no.

**Comment by silverwind** [comment]
Not sure what you mean, looks perfect for me. If GitHub uses media queries then we have to too.

**Comment by the-j0k3r** [comment]
lol, how can that look perfect to you? `.release-entry, ` is always visible no matter the width and it should be only visible dependant on width.

Were going in circles, its broken in all 3 browsers.

HERE
![broken nav](https://user-images.githubusercontent.com/31389848/44165014-87a90980-a0bf-11e8-91b3-8daeb44d6e35.gif)

**Comment by silverwind** [comment]
Ah, now I see. No idea why it didn't show before.

**Comment by the-j0k3r** [comment]
lol, now it is really fixed. ;) I was loosing my plot thinking Im going nuts.
