### ISSUE TITLE
Selected comment borders aren't being styled now

### ISSUE THREAD

**Issue by xt0rted** [StylishThemes/GitHub-Dark#877]
The `.timeilne-comment` rule has `!important` which is forcing the border to be `#484848` instead of the primary color.

* **Browser**: chrome
* **Operating System**: win10
* **Link to page with the issue**: https://github.com/StylishThemes/GitHub-Dark/pull/868#issuecomment-469344125
* **Screenshot**:

![image](https://user-images.githubusercontent.com/831974/54165361-bfe6af80-4436-11e9-89d2-3e8c1d0ba33e.png)

![image](https://user-images.githubusercontent.com/831974/54165401-e86ea980-4436-11e9-83f1-e0f374619031.png)

**Comment by xt0rted** [comment]
Not sure if it's related but the verified commit popup isn't fully styled now either.

![image](https://user-images.githubusercontent.com/831974/54165610-e1946680-4437-11e9-9ed8-2ea8d422e38b.png)

**Comment by the-j0k3r** [comment]
Fixed the verified dropdown in https://github.com/StylishThemes/GitHub-Dark/commit/6b33732a272b4fcd97adaa1b3d6819cc809d4632

**Comment by the-j0k3r** [comment]
Solved first issue by manually adding !important to `/* auto-generated rule for "border-color: #2188ff" */` section.

![Capture](https://user-images.githubusercontent.com/31389848/54181722-c3fae780-449f-11e9-91ea-c5664909cc59.PNG)


But idk how to override this in generator for this specifically. Manually though it probably would be possible by increasing specificity of the affected selectors.

**Comment by Mottie** [comment]
Bot has been pretty much disabled, but not uninstalled now. It's only set to work on the logo repo, because it's a pain to find and reinstall if we ever decide to do that.

**Comment by xt0rted** [comment]
This isn't fixed, or it was and broke again.

![image](https://user-images.githubusercontent.com/831974/54278869-08eb5080-456a-11e9-82b1-cf19b79d07b8.png)

**Comment by the-j0k3r** [comment]
Broke again... pff.

**Comment by the-j0k3r** [comment]
This is as good as I can do atm

```css
  .timeline-comment-group:target .timeline-comment::before {
    border-right-color: /*[[base-color]]*/;
    filter: drop-shadow(-.15em 0 0 /*[[base-color]]*/);
  }
  .timeline-comment-group:target .timeline-comment {
    border: 2px solid /*[[base-color]]*/ !important;;
    box-shadow: 0 0 0 .1em rgba(/*[[base-color-rgb]]*/, .8) !important;
  }
```
![Capture](https://user-images.githubusercontent.com/31389848/54294327-a5851100-45b1-11e9-8bbf-e0294d38ff0b.PNG)

![Capture](https://user-images.githubusercontent.com/31389848/54294353-ab7af200-45b1-11e9-89ba-a54258841703.PNG)

Its not as nice as it was... So feel free to improve on it or whatever works.

**Comment by silverwind** [comment]
Fixed this in https://github.com/StylishThemes/GitHub-Dark/commit/a82d9a813083f1bab781687c2157e9b8cdc5c5af.

**Comment by silverwind** [comment]
Also, triangle fixed in https://github.com/StylishThemes/GitHub-Dark/commit/721a1d31f28454a93f434c7f106f02030decac29.

**Comment by xt0rted** [comment]
This is partially fixed. The `box-shadow` isn't being applied correctly because of a (missing?) `!important`.

![image](https://user-images.githubusercontent.com/831974/54326064-8307ed80-45db-11e9-9756-4815032f6741.png)

![image](https://user-images.githubusercontent.com/831974/54326073-93b86380-45db-11e9-8ba8-862d9651e413.png)

The custom color isn't being applied at all to code comments https://github.com/StylishThemes/GitHub-Dark/commit/721a1d31f28454a93f434c7f106f02030decac29#r32734731.

![image](https://user-images.githubusercontent.com/831974/54326162-ef82ec80-45db-11e9-9234-f0a05d7303c6.png)

![image](https://user-images.githubusercontent.com/831974/54326189-0de8e800-45dc-11e9-986e-90926fcb48bf.png)

**Comment by xt0rted** [comment]
Found another spot that needs fixing (this is with what's in master at 570868dc9c803825975c6d60e06ec30c2273a869).

![image](https://user-images.githubusercontent.com/831974/54709838-a8858180-4b1c-11e9-92f2-6273b3c89c73.png)

https://github.com/StylishThemes/GitHub-Dark/pull/865#pullrequestreview-209884589

**Comment by silverwind** [comment]
Did a number of fixes related to those triangles, hopefully resolved now.

**Comment by the-j0k3r** [comment]
ye this seems fixed again =) so lets close it.

**Comment by the-j0k3r** [comment]
Actually no. This is still broken here https://github.com/StylishThemes/GitHub-Dark/commit/6c6d58de396d4d9096ecc07971ba7307a13da9a6#r32854380

Seems a border is missing. `border: 1px solid #2188ff;`

```css
.review-comment:target {
	border: 1px solid #2188ff;
	border-radius: 3px;
	box-shadow: 0 0 0 .2em #c8e1ff;
}
```

**Comment by silverwind** [comment]
Missed a border generator there, fixed in https://github.com/StylishThemes/GitHub-Dark/commit/3bc9865bf04744dd0541f5df10913685e7972d27.
